"""Training loop, data-fitting adapters, callbacks, and optimizer wrappers."""

from .callbacks import (
    BestCheckpointSaver,
    BestModelTracker,
    CSVLogger,
    Callback,
    ConsoleLogger,
    EarlyStopping,
    FinalCheckpointSaver,
    GradientNormMonitor,
    HistoryLogger,
    HistoryRecorder,
    LambdaCallback,
    LearningRateLogger,
    LossMonitor,
    LossPlotSaver,
    MaxTime,
    ParityPlotSaver,
    PeriodicCheckpointSaver,
    PredictionResultSaver,
    RegularizationReportSaver,
    RunSummaryLogger,
    TargetLossReached,
    TerminateOnNaN,
)
from .data_fitting import BinaryClassificationFitting, DataFitting, LatentOutputFitting, MultiClassClassificationFitting
from .model_handler import ModelHandler
from .optimizer import (
    Optimizer,
    constant_lr,
    cosine_annealing_lr,
    exponential_decay_lr,
    inverse_time_decay_lr,
    linear_warmup_lr,
    polynomial_decay_lr,
    step_decay_lr,
    warmup_decay_lr,
)
from .output_transforms import BaseOutputTransform, IdentityOutputTransform, InputProductOutputTransform

__all__ = [
    'BaseOutputTransform',
    'BestCheckpointSaver',
    'BestModelTracker',
    'BinaryClassificationFitting',
    'CSVLogger',
    'Callback',
    'ConsoleLogger',
    'DataFitting',
    'EarlyStopping',
    'FinalCheckpointSaver',
    'GradientNormMonitor',
    'HistoryLogger',
    'HistoryRecorder',
    'IdentityOutputTransform',
    'InputProductOutputTransform',
    'LambdaCallback',
    'LatentOutputFitting',
    'LearningRateLogger',
    'LossMonitor',
    'LossPlotSaver',
    'MaxTime',
    'ModelHandler',
    'MultiClassClassificationFitting',
    'Optimizer',
    'ParityPlotSaver',
    'PeriodicCheckpointSaver',
    'PredictionResultSaver',
    'RegularizationReportSaver',
    'RunSummaryLogger',
    'TargetLossReached',
    'TerminateOnNaN',
    'constant_lr',
    'cosine_annealing_lr',
    'exponential_decay_lr',
    'inverse_time_decay_lr',
    'linear_warmup_lr',
    'polynomial_decay_lr',
    'step_decay_lr',
    'warmup_decay_lr',
]
